    create table task (
       id bigint generated by default as identity,
        description varchar(250),
        score integer not null check (score>=1),
        status integer not null,
        title varchar(255),
        primary key (id)
    );

INSERT INTO TASK (title, description, score, status)
VALUES ('BD', 'Modelar o banco', 150, 0);
